services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nafs
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nafs"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    volumes:
      - .:/app
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - BUN_INSTALL_CACHE_DIR=/app/.bun-cache
      - NODE_ENV=development

  prisma-studio:
    image: oven/bun:1.1-slim
    working_dir: /app
    entrypoint: ["bunx", "prisma", "studio"]
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5555:5555"

volumes:
  postgres-data: